
file =open ("data.csv")
#file.seek(10)
#print (file.readline())
#print (file.read())
#print (file.readline())
#print (file.readline())
#print (file.read(5))
#print (file.read(10))
#lines = file.readlines()
#print (lines)